language: java
jdk:
        - oraclejdk11
before_install:
  - wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
  - tar xzvf apache-maven-3.6.3-bin.tar.gz
  - export PATH=`pwd`/apache-maven-3.6.3/bin:$PATH
  - mvn -v
script:
        - cd CodingDojo && mvn clean install "-Dmaven.test.excludes=**/PerformanceTest.java, **/cucumber/*.java"
cache:
  directories:
  - .autoconf
  - $HOME/.m2
dist: trusty