sudo: false
language: node_js

node_js:
  - '10'

addons:
  ssh_known_hosts: jschallenge.vreshch.com

script:
- npm install
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
- docker build --pull -t "vreshch/codenjoy-lb" .
- docker push "vreshch/codenjoy-lb"

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

notifications:
  email: false

before_install:
- openssl aes-256-cbc -K $encrypted_08a778432608_key -iv $encrypted_08a778432608_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
