version: '3.3'

services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
        codenjoy:
            ipv4_address: 172.28.1.6