version: '3.3'

services:
   wordpress_db:
     image: mysql:5.7
     container_name: wordpress-database
     volumes:
       - ./materials/wordpress/database:/var/lib/mysql
       - /etc/localtime:/etc/localtime:ro
#     ports:                                                               #P#
#       - "${WORDPRESS_MYSQL_PORT}:3306"                                   #P#
     restart: always
     environment:
         MYSQL_ROOT_PASSWORD: ${WORDPRESS_MYSQL_ROOT_PASSWORD}
         MYSQL_DATABASE: ${WORDPRESS_MYSQL_DATABASE}
         MYSQL_USER: ${WORDPRESS_MYSQL_USER}
         MYSQL_PASSWORD: ${WORDPRESS_MYSQL_PASSWORD}
     networks:
         codenjoy:
             ipv4_address: 172.28.1.7

   wordpress:
     depends_on:
       - wordpress_db
     image: wordpress:latest
     container_name: wordpress
     volumes:
       - ./materials/wordpress/wp_content:/var/www/html/wp-content
       - /etc/localtime:/etc/localtime:ro
#     ports:                                                               #P#
#       - "${WORDPRESS_PORT}:80"                                           #P#
     restart: always
     environment:
         WORDPRESS_DB_HOST: wordpress_db:3306
         WORDPRESS_DB_USER: ${WORDPRESS_MYSQL_USER}
         WORDPRESS_DB_PASSWORD: ${WORDPRESS_MYSQL_PASSWORD}
     networks:
         codenjoy:
             ipv4_address: 172.28.1.8

   nginx:
     depends_on:
       - wordpress
     volumes:
       - ./config/nginx/conf.d/wordpress/upstreams.conf:/etc/nginx/conf.d/wordpress/upstreams.conf
       - ./config/nginx/conf.d/wordpress/locations.conf:/etc/nginx/conf.d/wordpress/locations.conf