log:
  debug: true
  filter: >
    com.codenjoy,
    com.codenjoy.dojo.services.jdbc,
    org.eclipse.jetty,
    org.springframework.mvc
logging:
  level:
    com:
      codenjoy: debug
    org:
      eclipse.jetty: debug
      springframework.mvc: debug